name: Package

on:
  push:

jobs:
  package:
    strategy:
      matrix:
        node: [14, 15, 16]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Package
      run: npm pack
